### ISSUE TITLE
Navigation tabs broken and overflow on Chrome; caused by em rounding

### ISSUE THREAD

**Issue by gocom** [textpattern/textpattern-forum#42]
On Chrome the navigation tabs go 1px over the border the ul has. On Firefox this does not happen. This is caused by the em based padding rule and its rounding and the negative margin that uses pixels.

``` css
a {
    margin: -1px;
    padding: 0.5384615em 1em;
}
```

On Chrome the resulting ul is 35px tall while the tabs are 36 pixels. On Firefox both are 36pixels. Chrome basically doesn't know what it should draw, so it draws an extra pixel.

Instead of 0.5384615em, it should be 0.5384616em.
